### ISSUE TITLE
Pretrained weights expired

### ISSUE THREAD

**Issue by May-226** [DaoyiG/TC-Depth#10]
This link is expired and cannot be used anymore.

**Comment by May-226** [comment]
Also, is there any way to not use pretrained weights, but train a model from scratch?

**Comment by DaoyiG** [comment]
Hey,

Maybe try this one:

https://drive.google.com/file/d/189C9xUhwwwVgPT7qU_v5hPSw9FzivYhF/view?usp=share_link

For not using any pre-trained weights, you could modify the trainer script to let the reference depth model train alongside.
