### ISSUE TITLE
About Temporal Consistency Metric (TCM)

### ISSUE THREAD

**Issue by longyangqi** [DaoyiG/TC-Depth#2]
Awesome work!  Looking forward to the code.

Before that, I want to get more details about the `Temporal Consistency Metric (TCM)` described in Section4 of your paper.

Could you share the code of TCM or give a more detailed descriptions on how to build this metric?

Thanks a lot!

**Comment by HanzhiC** [comment]
Hi, thanks for your interest! 
We will release the code (and also scripts for TCM) by the end of November ;)

In short: TCM is essentially a measurement of the overlapping degree of sets of point clouds, say if you have super consistent depth across views, then after lifting them to 3D and transformed to the same frame, they will be exactly overlapped with their correspondence.  Our TCM is used to match how good this overlapping degree is.

**Comment by longyangqi** [comment]
> Hi, thanks for your interest! We will release the code (and also scripts for TCM) by the end of November ;)
> 
> In short: TCM is essentially a measurement of the overlapping degree of sets of point clouds, say if you have super consistent depth across views, then after lifting them to 3D and transformed to the same frame, they will be exactly overlapped with their correspondence. Our TCM is used to match how good this overlapping degree is.

Thanks for your reply!

**Comment by DaoyiG** [comment]
For a better understanding of the metric, you can also check out our supplementary file under this link:
[Supplementary Material](https://mediatum.ub.tum.de/doc/1633983/1633983.pdf)

**Comment by longyangqi** [comment]
Thank you for releasing the evaluation code!

I have noticed that the `tcm_test_files.txt` is used. And there are 212 files in the split, some of which are not in Eigen splits with 697 files. I wonder how to choose these files? By some criteria or just by random?

**Comment by HanzhiC** [comment]
Hi,

Yes, we selected the testing split for TCM randomly, while we do manually add some snippets with rotation motion since most of the motion in KITTI is pure translation.

**Comment by zhangjinsong3** [comment]
Awesome work! 
Wander to know how to generate rhe `gt_temp_components_{}frames.npz` file or the `gt_data["flow"]`
