### ISSUE TITLE
About Spatial Attention Layer

### ISSUE THREAD

**Issue by big-chan** [DaoyiG/TC-Depth#5]
Hi, this seems very interesting

I have a question about the spatial attention layer's operation process.

![image](https://user-images.githubusercontent.com/41200134/155322056-02f39cce-6f85-4ffb-a883-806e1ded8ccb.png)

In the eq.3, Pi and Pj are treated as key and query, right?
But I don't know exactly where the key and query come from. I'm guessing that the key and query will come out as shown in the picture. Is it right?

![image](https://user-images.githubusercontent.com/41200134/155323236-b3f86861-38dc-4245-9877-2225c92e693e.png)

I can't seem to find about the input of the model. 
Does this model need 3 frames as input in the inference time?

**Comment by HanzhiC** [comment]
Hi, thanks for the interest and sorry for the late reply. As Daoyi and I are busy with our master thesis recently.
1. We slightly abuse the notation for attention. In spatial attention, there is no key and query. The attention is sorely established through the spatial distance between any 2 given points. This process is like a "self-attention" scheme, as we don't establish any correlation across temporal frames. Each frame from a snippet has its own "spatial attention" to aggregate its features.
2. Yes. We input 3 frames to acquire local information. While the temporal consistency can preserve quite well for an even larger time window. (see TCM results for 5, 7 frames.)
