### ISSUE TITLE
Temporal Consistency Metric reproducibility

### ISSUE THREAD

**Issue by zshn25** [DaoyiG/TC-Depth#9]
Could you please share the code for generating the .npz files for predictions and GT? There are 3 such configurations for different snippet sizes.

Thank you

**Comment by HanzhiC** [comment]
The export script for depth prediction is exported for TCM evaluation, please check out [here](https://github.com/DaoyiG/TC-Depth/blob/main/export_snippet_pred.py). We don't intend to share the script for GT generation, you can download GT via our provided link. You can also refer to the following structure to customize your own GT:

`
gt_temp_components: {
             depth: {
                     0: sparse original lidar depth at the target frame  
                    -1: dense interpolated lidar depth at source frame -1
                     1: dense interpolated lidar depth at source frame 1
                    }

              pose: {
                    -1: pose from 0 to -1
                     1: pose from 0 to 1
                    }

              flow: {
                    -1: warping flow between 0 and -1 
                     1: warping flow between 0 and 1
                    }
                    }
`

Hope it can help :)
